development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:482f4f19acb1df41b2bcc6e0a86546bf@pearlfish.redistogo.com:9016/
  channel_prefix: message_me_production
